#!/usr/bin/env python3
"""Extract Overwatch CMF per-build keytables from CascLib.

Reads CascLib/src/overwatch/cmf-key.cpp, finds every
``namespace KeyCMF_<NNNNNN>`` block, extracts the 512-byte ``Keytable[]``
array, and emits a single generated Go file
``internal/root/overwatch/cmfkeys/keytables_generated.go``.

The per-build ``Key()`` / ``IV()`` derivation functions are NOT ported —
their formulas vary across all 179 builds and a faithful port is a
separate effort tracked in rewriting_plan.md §6.1. Exposing the raw
keytables is the first step: callers writing a custom ``KeyProvider``
for a specific build can grab the table by build number rather than
copying it out of the C++ source by hand.

Usage:

    python3 tools/cmfkeygen/main.py
"""

from __future__ import annotations

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SRC = REPO / "CascLib" / "src" / "overwatch" / "cmf-key.cpp"
OUT = REPO / "internal" / "root" / "overwatch" / "cmfkeys" / "keytables_generated.go"
OUT_FUNCS = REPO / "internal" / "root" / "overwatch" / "cmfkeys" / "keyfuncs_generated.go"

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from translate import translate_namespace

NAMESPACE_RE = re.compile(r"namespace KeyCMF_(\d+)\s*\{")
KEYTABLE_RE = re.compile(
    r"static const BYTE Keytable\[\]\s*=\s*\{(.*?)\};",
    re.DOTALL,
)
HEX_RE = re.compile(r"0[xX]([0-9a-fA-F]{1,2})")


def main() -> int:
    if not SRC.exists():
        print(f"missing source: {SRC}", file=sys.stderr)
        return 1

    text = SRC.read_text(encoding="utf-8", errors="replace")

    builds: list[tuple[int, list[int]]] = []
    scopes: dict[int, str] = {}
    for ns in NAMESPACE_RE.finditer(text):
        build = int(ns.group(1))
        # Slice from this namespace open up to the next namespace open
        # (or end of file) — that's the scope where this build's
        # Keytable lives.
        start = ns.end()
        nxt = NAMESPACE_RE.search(text, start)
        end = nxt.start() if nxt else len(text)
        scope = text[start:end]
        scopes[build] = scope

        m = KEYTABLE_RE.search(scope)
        if not m:
            print(f"warning: no Keytable[] in build {build}", file=sys.stderr)
            continue

        bytes_ = [int(b, 16) for b in HEX_RE.findall(m.group(1))]
        if len(bytes_) != 512:
            print(
                f"warning: build {build} keytable has {len(bytes_)} bytes (want 512)",
                file=sys.stderr,
            )
            continue

        builds.append((build, bytes_))

    builds.sort(key=lambda kv: kv[0])

    out_lines: list[str] = []
    out_lines.append("// Code generated by tools/cmfkeygen/main.py. DO NOT EDIT.")
    out_lines.append("//")
    out_lines.append(
        "// Source: CascLib/src/overwatch/cmf-key.cpp (originally TACTLib)."
    )
    out_lines.append("")
    out_lines.append("package cmfkeys")
    out_lines.append("")
    out_lines.append(f"// builtinKeytableCount is the number of ported builds ({len(builds)}).")
    out_lines.append(f"const builtinKeytableCount = {len(builds)}")
    out_lines.append("")
    out_lines.append("// builtinKeytables maps build number to its 512-byte CMF keytable.")
    out_lines.append("var builtinKeytables = map[uint32][512]byte{")

    for build, bytes_ in builds:
        out_lines.append(f"\t{build}: {{")
        for row_start in range(0, 512, 16):
            row = bytes_[row_start : row_start + 16]
            out_lines.append("\t\t" + ", ".join(f"0x{b:02X}" for b in row) + ",")
        out_lines.append("\t},")

    out_lines.append("}")
    out_lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"wrote {len(builds)} keytables to {OUT.relative_to(REPO)}")

    # ---- per-build Key()/IV() Go translations ----
    func_lines: list[str] = []
    func_lines.append("// Code generated by tools/cmfkeygen/main.py. DO NOT EDIT.")
    func_lines.append("//")
    func_lines.append("// Per-build Key()/IV() translations from")
    func_lines.append("// CascLib/src/overwatch/cmf-key.cpp.")
    func_lines.append("")
    func_lines.append("package cmfkeys")
    func_lines.append("")
    func_lines.append('import "github.com/ldmonster/go-casclib/internal/root/overwatch"')
    func_lines.append("")
    func_lines.append("// maxInt32 is used by translated Math.Max() expressions.")
    func_lines.append("func maxInt32(a, b int32) int32 { if a > b { return a }; return b }")
    func_lines.append("")
    func_lines.append("// builtinKeyFuncs maps build → translated Key() function.")
    func_lines.append("var builtinKeyFuncs = map[uint32]keyFunc{")

    n_key = 0
    n_iv = 0
    n_skipped_key = 0
    n_skipped_iv = 0
    iv_blocks: list[str] = []

    for build, _ in builds:
        scope = scopes[build]
        key_t, iv_t = translate_namespace(scope)
        if key_t and key_t.ok:
            n_key += 1
            func_lines.append(
                f"\t{build}: func(hdr overwatch.CMFHeader, keytable *[512]byte, "
                "buffer []byte, length int) {"
            )
            func_lines.append("\t\t_ = hdr")
            for ln in key_t.body.splitlines():
                func_lines.append("\t\t" + ln if ln else "")
            func_lines.append("\t},")
        else:
            n_skipped_key += 1

        if iv_t and iv_t.ok:
            n_iv += 1
            iv_blocks.append(
                f"\t{build}: func(hdr overwatch.CMFHeader, keytable *[512]byte, "
                "digest [20]byte, buffer []byte, length int) {\n"
                "\t\t_ = hdr\n"
                "\t\t_ = digest\n"
                + "\n".join(("\t\t" + ln if ln else "") for ln in iv_t.body.splitlines())
                + "\n\t},"
            )
        else:
            n_skipped_iv += 1

    func_lines.append("}")
    func_lines.append("")
    func_lines.append("// builtinIVFuncs maps build → translated IV() function.")
    func_lines.append("var builtinIVFuncs = map[uint32]ivFunc{")
    for blk in iv_blocks:
        func_lines.append(blk)
    func_lines.append("}")
    func_lines.append("")

    OUT_FUNCS.write_text("\n".join(func_lines), encoding="utf-8")
    print(
        f"wrote {n_key} Key + {n_iv} IV translations "
        f"(skipped {n_skipped_key} Key, {n_skipped_iv} IV) "
        f"to {OUT_FUNCS.relative_to(REPO)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
