// Copyright 2026 go-casclib Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package compress

import (
	"bytes"
	"testing"
)

// TestUnbzip2KAT verifies bzip2 decompression with a known-answer vector.
// The compressed bytes were generated by: echo -n "hello bzip2 test" | bzip2
func TestUnbzip2KAT(t *testing.T) {
	compressed := []byte{
		0x42, 0x5a, 0x68, 0x39, 0x31, 0x41, 0x59, 0x26, 0x53, 0x59, 0x8a, 0x52,
		0xb8, 0xda, 0x00, 0x00, 0x03, 0x19, 0x80, 0x40, 0x00, 0x10, 0x00, 0x12,
		0x64, 0xcc, 0x10, 0x20, 0x00, 0x22, 0x00, 0x0c, 0x84, 0x0d, 0x03, 0x43,
		0x1f, 0x62, 0xc2, 0x1d, 0x08, 0x1e, 0xc9, 0xf1, 0x77, 0x24, 0x53, 0x85,
		0x09, 0x08, 0xa5, 0x2b, 0x8d, 0xa0,
	}
	want := []byte("hello bzip2 test")

	got, err := Unbzip2(compressed, len(want))
	if err != nil {
		t.Fatalf("Unbzip2: %v", err)
	}

	if !bytes.Equal(got, want) {
		t.Errorf("got %q, want %q", got, want)
	}
}

func TestUnbzip2BadInput(t *testing.T) {
	if _, err := Unbzip2([]byte{0x00, 0x01, 0x02}, 0); err == nil {
		t.Error("expected error for bad bzip2 input")
	}
}
